# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def shared_pods
    pod "tealium-swift"
end

target 'WatchPuzzle' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WatchPuzzle
  shared_pods
end

target 'WatchPuzzle_WatchKit_App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WatchPuzzle WatchKit App
  shared_pods
end

target 'WatchPuzzle_WatchKit_Extension' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  platform :watchos, '3.2'
  # Pods for WatchPuzzle WatchKit Extension
  shared_pods
end
