# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Swift-WKWebView' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SegueCatalog
	pod "tealium-swift", :path => '../../tealium-swift.podspec'
end
