included:
  - ../../support/tests
excluded:
  - Tests/SwiftLintFrameworkTests/Resources
disabled_rules:
  - force_cast
  - force_try
  - line_length
  - file_length
  - identifier_name
  - trailing_comma
  - unused_optional_binding
  - overridden_super_call
  - vertical_parameter_alignment_on_call
  - cyclomatic_complexity
  - type_body_length
  - file_header
opt_in_rules:
  - explicit_init
  - closure_spacing
  - redundant_nil_coalescing
  - private_outlet
  - nimble_operator
  - attributes
  - operator_usage_whitespace
  - closure_end_indentation
  - first_where
  - sorted_imports
  - object_literal
  - prohibited_super_call
  - fatal_error_message
  - unneeded_parentheses_in_closure_argument
  - extension_access_modifier
  - pattern_matching_keywords
  - array_init
  - literal_expression_end_indentation
  - number_separator

file_header:
  required_pattern: |
                    \/\/
                    \/\/  .*?\.swift
                    \/\/  tealium-swift
                    \/\/
                    \/\/  Created by .*? on \d{1,2}\/\d{1,2}\/\d{2}\.
                    \/\/  Copyright © \d{4} Tealium, Inc\. All rights reserved\.
                    \/\/
identifier_name:
  excluded:
    - id
  severity: warning
number_separator:
  minimum_length: 5

custom_rules:
  rule_id:
    included: Source/SwiftLintFramework/Rules/\w+\.swift
    name: Rule ID
    message: Rule IDs must be all lowercase, snake case and not end with `rule`
    regex: identifier:\s*("\w+_rule"|"\S*[^a-z_]\S*")
    severity: error
  any_observable_generics:
    included: ./tealium
    name: ToAnyObservable Generics
    message: ToAnyObservable must always specify Generics type to avoid compile issues
    regex: \@ToAnyObservable\s*\(
    severity: error
