included:
  - ./tealium
excluded:
  - ./builder/Tests/SwiftLintFrameworkTests/Resources
  - ./tealium/core/DiskStorage/Disk/
  - ./tealium/core/utils/AnyCodable/
  - ./tealium/core/utils/Data+Gzip/
  - ./builder/iOSTealiumMediaTest/
  - ./builder/iOSTealiumTest/
  - ./builder/macOSTealiumTest/
  - ./builder/tvOSTealiumTest/
disabled_rules:
  - trailing_comma
  - unused_optional_binding
  - file_header
opt_in_rules:
  - force_unwrapping
  - explicit_init
  - closure_spacing
  - overridden_super_call
  - redundant_nil_coalescing
  - private_outlet
  - nimble_operator
  - attributes
  - operator_usage_whitespace
  - closure_end_indentation
  - first_where
  - sorted_imports
  - object_literal
  - prohibited_super_call
  - fatal_error_message
  - vertical_parameter_alignment_on_call
  - unneeded_parentheses_in_closure_argument
  - extension_access_modifier
  - pattern_matching_keywords
  - array_init
  - literal_expression_end_indentation
  - number_separator

identifier_name:
  excluded:
    - id
  severity: warning
line_length: 200
number_separator:
  minimum_length: 5
large_tuple: 4

custom_rules:
  rule_id:
    included: Source/SwiftLintFramework/Rules/\w+\.swift
    name: Rule ID
    message: Rule IDs must be all lowercase, snake case and not end with `rule`
    regex: identifier:\s*("\w+_rule"|"\S*[^a-z_]\S*")
    severity: error
