# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TealiumSwiftExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TealiumSwiftExample
  pod "tealium-swift", "1.8.0-beta3"

end

target 'TealiumSwiftWatchExample Extension' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TealiumSwiftWatchExample Extension
  #pod "tealium-swift", "1.8.0-beta3"
  pod "tealium-swift/Core", "1.8.0-beta3"
  pod "tealium-swift/TealiumAppData", "1.8.0-beta3"
  pod "tealium-swift/TealiumCollect", "1.8.0-beta3"
  pod "tealium-swift/TealiumConsentManager", "1.8.0-beta3"
  pod "tealium-swift/TealiumDelegate", "1.8.0-beta3"
  pod "tealium-swift/TealiumDeviceData", "1.8.0-beta3"
  pod "tealium-swift/TealiumDispatchQueue", "1.8.0-beta3"
  pod "tealium-swift/TealiumLifecycle", "1.8.0-beta3"
  pod "tealium-swift/TealiumLogger", "1.8.0-beta3"
  pod "tealium-swift/TealiumVolatileData", "1.8.0-beta3"
  pod "tealium-swift/TealiumVisitorService", "1.8.0-beta3"
end

target 'TealiumSwiftTVExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TealiumSwiftWatchExample Extension
  #pod "tealium-swift", "1.8.0-beta3"
  pod "tealium-swift/Core", "1.8.0-beta3"
  pod "tealium-swift/TealiumAppData", "1.8.0-beta3"
  pod "tealium-swift/TealiumCollect", "1.8.0-beta3"
  pod "tealium-swift/TealiumConsentManager", "1.8.0-beta3"
  pod "tealium-swift/TealiumConnectivity", "1.8.0-beta3"
  pod "tealium-swift/TealiumDelegate", "1.8.0-beta3"
  pod "tealium-swift/TealiumDeviceData", "1.8.0-beta3"
  pod "tealium-swift/TealiumDispatchQueue", "1.8.0-beta3"
  pod "tealium-swift/TealiumLifecycle", "1.8.0-beta3"
  pod "tealium-swift/TealiumLogger", "1.8.0-beta3"
  pod "tealium-swift/TealiumVolatileData", "1.8.0-beta3"
  pod "tealium-swift/TealiumVisitorService", "1.8.0-beta3"
end  