# Uncomment the next line to define a global platform for your project
  platform :ios, '12.0'

target 'FirebaseSample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FirebaseSample

  # Tealium
  pod "tealium-swift/Core"
  pod "tealium-swift/TealiumAppData"
  pod "tealium-swift/TealiumConnectivity"
  pod "tealium-swift/TealiumDataSource"
  pod "tealium-swift/TealiumDelegate"
  pod "tealium-swift/TealiumDeviceData"
  pod "tealium-swift/TealiumDispatchQueue"
  pod "tealium-swift/TealiumLifecycle"
  pod "tealium-swift/TealiumLogger"
  pod "tealium-swift/TealiumRemoteCommands"
  pod "tealium-swift/TealiumTagManagement"
  pod "tealium-swift/TealiumVolatileData"
  pod "tealium-swift/TealiumDefaultsStorage"

  # Firebase
  pod 'Firebase/Core'

end
