# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TealiumMediaExample' do
  platform :ios, '14.0'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TealiumMediaExample
  pod 'tealium-swift', :path=> '../../'

end
