name: Uploads XCFrameworks to Release

on:
  release:
    types:
      - created
jobs:
  upload:
    name: Upload XCFrameworks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Upload   
        uses: AButler/upload-release-assets@v2.0
        with:
          files: './tealium-xcframeworks.zip'
          repo-token: ${{ secrets.GITHUB_TOKEN }}  